config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'application#index'

  resources :games do
    collection do
      get :search, to: 'games#search', as: :search
      get "new_from_gb/:game", to: 'games#new_from_gb', as: :new_from_gb
    end
  end

  resources :users
  resources :wishlists do
    collection do
      get "new_from_gb/:game", to: 'wishlists#new_from_gb', as: :new_from_gb
    end
  end

  resources :queries
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  validates_uniqueness_of :game, scope: :user
end

app/models/game.rb
class Game < ActiveRecord::Base

  serialize :themes
  serialize :developers
  serialize :release_platforms

  has_attached_file :cover, styles: {
    large:  '500x700>',
    medium: '200x300>',
    thumb:  '200x200>'
  },
  default_url: '/images/:style/missing.png'

  do_not_validate_attachment_file_type :cover

  validates_uniqueness_of :api_reference

  has_one :wiki

  has_many :collections
  has_many :users, through: :collections

  has_and_belongs_to_many :genres

  def to_param
    [id, name.parameterize].join('-')
  end

  def self.search(game)
    @search = GiantBomb::Search.new
    @search.offset(100)
    @search.limit(10)
    @search.resources('game')
    @search.query(game)

    return @search.fetch
  end

  # Creates a local copy of the Games based on it's ID from GiantBomb' API
  #
  def self.new_from_gb(id, user)

    data = {
      field_list: 'name'
    }
    game = GiantBomb::Game.detail(id, data)


    developers = []

    game.developers.each do |game_developer|
      developers << developer = { name: game_developer['name'], url: game_developer['site_detail_url'], api_reference: game_developer['id'] }
    end

    publishers = []

    game.publishers.each do |game_publisher|
      publishers << publisher = { name: game_publisher['name'], url: game_publisher['site_detail_url'], api_reference: game_publisher['id'] }
    end

    genres = []
    unless game.genres.nil?
      game.genres.each do |game_genre|

        genre = Genre.find_or_create_by(api_reference: game_genre['id']) do |genre|
          genre.name = game_genre['name']
          genre.url = game_genre['site_detail_url']
          genre.api_reference = game_genre['id']
        end

        genres << genre
      end
    end

    platforms = []
    game.platforms.each do |game_platform|
      platforms << platform = { name: game_platform['name'], abbr: game_platform['abbreviation'], url: game_platform['site_detail_url'], api_reference: game_platform['id'] }
    end

    themes = []

    unless game.themes.nil?
      game.themes.each do |game_theme|
        themes << theme = { name: game_theme['name'], url: game_theme['site_detail_url'], api_reference: game_theme['id'] }
      end
    end

    @game = Game.find_by_api_reference(game.id)

    if @game.nil?

      Rails.logger.info "the game does not exists!"

      gg = Game.new
      gg.name     = game.name
      gg.aliases  = game.aliases

      gg.genres     = genres
      gg.themes     = themes
      gg.developers = developers

      gg.description  = game.deck
      gg.cover        = game.image['super_url']
      gg.release_date = game.original_release_date

      gg.release_platforms = platforms
      gg.api_endpoint  = game.api_detail_url
      gg.api_reference = game.id

      gg.users        = [user]
      gg.save

      w = Wiki.find_or_create_by(game_id: gg.id) do |ww|

        ww.game_id = gg.id

        ww.body       = game.description
        ww.publishers = publishers
        ww.save
      end
    else
      Collection.create(user: user, game: @game)
    end
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collections
  has_many :games, through: :collections
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  serialize :publishers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, only: [:index]

  def index
    @games = current_user.games

    render 'application/dashboard'
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new, :create, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  def search
    @games = Game.search(params[:query])
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_from_gb
    Game.new_from_gb(params[:game], current_user)
    redirect_to root_path

    # render json: @game
  end

private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(
      :name,
      :aliases,
      :description,
      :cover,
      :release_date,
      :release_platforms,
      :themes,
      :developers,
      :api_endpoint,
      :api_reference,
      :user_ids,
      :genres_ids
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_game
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :game_ids
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/dashboard.html.slim
.cell-xs-12.cell-sm-3.cell-md-2

  .panel.panel-default
    .panel-heading
      h4
        = current_user.email

    .panel-body
      ul.list
        li
          h6.user-info-heading Member since
          p.user-info-content
            = time_ago_in_words(current_user.created_at)

        li
          h6.user-info-heading Your last visit
          p.user-info-content
            = "#{time_ago_in_words(current_user.last_sign_in_at)} ago"

.cell-xs-12.cell-sm.cell-md

  .games.games--dashboard.games--list

    - @games.each do |g|

      .row.game
        .cell-xs-2

          .game-image
            = image_tag(g.cover.url(:original), alt: g.name, class: 'img-responsive')

        .cell-xs-7

          .game-body

            .row
              .cell-xs

                .game-title
                  h2
                    = link_to(g.name, game_path(g.to_param))

                  .game-aliases
                    span.game-title-info
                      = g.aliases

              .cell-xs-2
                .game-rating
                  p.game-body-content

                    - g.collections.first.rating.times do |s|
                      = fa_icon('star')

            .game-description
              h6.game-body-heading Description
              p.game-body-content
                = g.description

            .row

              .cell-sm-3

                .game-date-added
                  h6.game-body-heading Date added
                  p.game-body-content.tooltip-left data-tooltip="#{Collection.find_by_game_id(g).created_at}"
                    = "#{time_ago_in_words(Collection.find_by_game_id(g).created_at)} ago"

              .cell-sm-3

                .game-platforms
                  h6.game-body-heading Platform
                  p.game-body-content
                    = link_to(g.collections.first.platform, '#comingsoon', class: 'link badge')

              .cell-sm

                .game-genre
                  h6.game-body-heading
                    = g.genres.count > 1 ? 'Genres' : 'Genre'

                  p.game-body-content
                    = g.genres.map { |g| link_to(g.name, '#comingsoon', class: 'link badge') }.join.html_safe

        .cell-xs-3

          .game-body

            .game-release-date
              h6.game-body-heading Release Date
              p.game-body-content.tooltip-left data-tooltip="#{g.release_date}"
                = "#{time_ago_in_words(g.release_date)} ago"

            .game-theme
              h6.game-body-heading
                = g.themes.count > 1 ? 'Themes' : 'Theme'

              ul.game-body-content.list

                - g.themes.each do |t|

                  li
                    = link_to(t[:name], '#comingsoon', class: 'link')

            .game-developer
              h6.game-body-heading
                = g.developers.count > 1 ? 'Developers' : 'Developer'

              p.game-body-content

                - g.developers.map do |d|

                  - if g.developers.count < 2

                    = d[:name]

                  - else

                    = "- #{d[:name]}"

                  br

app/views/games/index.html.slim
.notice
  = notice

.games

  - @games.each do |g|

    .row.game
      .cell-sm-2

        .game-image
          = image_tag(g.cover.url(:original), alt: g.name, class: 'img-responsive')

      .cell-sm.game-body
        .row
          .cell-sm-12

            .row
              .cell-sm

                .game-title
                  h2
                    = link_to(g.name, game_path(g.to_param))

              .cell-sm-3
                .game-rating
                  p.game-body-content
                    = fa_icon('star')
                    = fa_icon('star')
                    = fa_icon('star')
                    = fa_icon('star')
                    = fa_icon('star')

          .cell-sm-12
            .game-description
              = g.description

            .game-else
              ul.list

                - Game.find_by_api_reference(g.api_reference).users.each do |u|

                  li
                    = u.email

app/views/games/search.html.slim
- if params[:query]

  - if @games.nil?

    = "Nothing found for '<span>#{params[:query]}</span>'".html_safe

  - else

    = "Your search term for '<span>#{params[:query]}</span>' returned <span>#{@games.count}</span> results.".html_safe

    .games.games--search.games--list

      - @games.each do |g|

        .row.game
          .cell-sm
            .row

              .cell-sm-2

                .game-image
                  = image_tag(g['image']['thumb_url'], alt: g['name']) if g['image']

              .cell-sm.game-body

                .game-title
                  h2
                    = g['name']

                  .game-aliases
                    span.game-title-info
                      = g['aliases'].split("\n").join(', ') if g['aliases']

                .game-description
                  h6.game-body-heading Description
                  p.game-body-content
                    = g['deck']

                .game-platforms
                  h6.game-body-heading Platforms
                  p.game-body-content

                    - if g['platforms']
                      - g['platforms'].map do |p|
                        = link_to(p['abbreviation'], '#comingsoon', class: 'link badge')

              .cell-sm-3.game-body

                .game-actions

                  - game = Game.find_by_api_reference(g['id'])

                  - if Collection.where({ game_id: game.try(:id), user_id: current_user.id }).exists?

                    = link_to 'Remove from my Games', '', class: 'btn btn-warning'

                  - else

                    = link_to 'Add to my Games', new_from_gb_games_path(g['id']), class: 'btn btn-success'

                .game-release-date
                  h6.game-body-heading Release Date

                  - if g['original_release_date']

                    p.game-body-content.tooltip-left data-tooltip="#{g['original_release_date']}"
                      = "#{time_ago_in_words(g['original_release_date'])} ago"

                .game-genre
                  h6.game-body-heading Genre
                  p.game-body-content
                    = g['genres']

- else

  .alert.alert-info
    p
      = "Start by searching a game"

app/views/games/show.html.slim
.row.game
  .cell-sm-2

    .game-image
      = image_tag(@game.cover.url(:original), alt: @game.name, class: 'img-responsive')

  .cell-sm.game-body
    .row
      .cell-sm-12

        .row
          .cell-sm

            .game-title
              h2
                = link_to(@game.name, game_path(@game.to_param))

          .cell-sm-3
            .game-rating
              p.game-body-content
                = fa_icon('star')
                = fa_icon('star')
                = fa_icon('star')
                = fa_icon('star')
                = fa_icon('star')

      .cell-sm-12
        .game-description
          = @game.description

.row
  .cell-sm

    .game
      = @game.wiki.body.html_safe

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta content='IE=edge' http-equiv='X-UA-Compatible'

    meta name='author' content='Vlad Radulescu @ Studio51'
    meta name='description' content='Create an maintain your games collection on the Cloud'

    meta name='viewport' content='width=device-width, initial-scale=1'

    title
      = 'games.directory'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags

  body

    header.header

      .grid

        nav.navbar
          .navbar-header
            = link_to 'games.directory', '#', class: 'navbar-brand'

          .navbar-collapse
            .navbar-form
              = form_tag search_games_path, method: :get do |f|
                = text_field_tag 'query', params[:query], class: 'form-control', autofocus: true, placeholder: 'start by searching and adding games to your collection..'

            ul.nav.navbar-nav
              li.navbar-item
                = link_to fa_icon('gamepad', text: 'games'), games_path, class: 'navbar-item-link'

              li.navbar-item
                = link_to 'you', root_path, class: 'navbar-item-link'

    main.main

      .grid
        .row

          = yield


    footer.footer

      .grid

        .row
          .cell-sm

            p
              = "Built with all the love in the world by #{link_to('Vlad Radulescu', 'https://twitter.com/pacMakaveli90')}".html_safe

            p
              = "Released under MIT License, #{link_to('open source', 'https://github.com/pacMakaveli/mygames.io')}".html_safe

          .cell-sm

            h6 Credits

            ul.list-inline
              li
                = "API: #{link_to('GiantBomb.com', '//giantbomb.com')}".html_safe
              li
                = "Colors: #{link_to('coolors.co', '//coolors.co')}".html_safe
              li
                = "Fonts: #{link_to('FontAwesome.io', '//fontawesome.io')}".html_safe

    = javascript_include_tag 'application', 'data-turbolinks-track' => true